2025-07-13 17:40:59,920 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-07-13 17:40:59,920 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 17:40:59,929 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-07-13 17:40:59,929 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 17:40:59,936 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-07-13 17:40:59,936 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 17:40:59,941 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 17:40:59,959 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 17:40:59,959 - sqlalchemy.engine.Engine - INFO - [generated in 0.00204s] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 17:40:59,982 - sqlalchemy.engine.Engine - INFO - INSERT INTO file_metadata (file_id, user_id, filename, file_size, file_type, upload_time, stored_filename) VALUES (%s, %s, %s, %s, %s, %s, %s)
2025-07-13 17:40:59,983 - sqlalchemy.engine.Engine - INFO - [generated in 0.00125s] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372', '{user_id}', '绘图4.eddx', 53466, 'application/octet-stream', datetime.datetime(2025, 7, 13, 17, 40, 59, 976528), '{user_id}_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx')
2025-07-13 17:40:59,987 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-07-13 17:41:00,005 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 17:41:00,008 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.id = %s
2025-07-13 17:41:00,012 - sqlalchemy.engine.Engine - INFO - [generated in 0.00340s] (2,)
2025-07-13 17:41:00,022 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-13 17:53:40,965 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 17:53:40,965 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 17:53:40,965 - sqlalchemy.engine.Engine - INFO - [cached since 761s ago] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 17:53:40,974 - sqlalchemy.engine.Engine - INFO - INSERT INTO file_metadata (file_id, user_id, filename, file_size, file_type, upload_time, stored_filename) VALUES (%s, %s, %s, %s, %s, %s, %s)
2025-07-13 17:53:40,974 - sqlalchemy.engine.Engine - INFO - [cached since 761s ago] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372', 'userid_123', '绘图4.eddx', 53466, 'application/octet-stream', datetime.datetime(2025, 7, 13, 17, 53, 40, 974847), 'userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx')
2025-07-13 17:53:40,985 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-07-13 17:53:41,001 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 17:53:41,001 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.id = %s
2025-07-13 17:53:41,004 - sqlalchemy.engine.Engine - INFO - [cached since 761s ago] (3,)
2025-07-13 17:53:41,004 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-13 18:43:48,773 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 18:43:48,773 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 18:43:48,773 - sqlalchemy.engine.Engine - INFO - [cached since 3769s ago] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 18:43:48,780 - __main__ - INFO - File with file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372 already exists. Returning existing file info.
2025-07-13 18:43:48,780 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-13 22:23:13,156 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-07-13 22:23:13,156 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 22:23:13,178 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-07-13 22:23:13,178 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 22:23:13,187 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-07-13 22:23:13,187 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 22:23:13,190 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 22:23:13,202 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 22:23:13,202 - sqlalchemy.engine.Engine - INFO - [generated in 0.00122s] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 22:23:13,228 - sqlalchemy.engine.Engine - INFO - INSERT INTO file_metadata (file_id, user_id, filename, file_size, file_type, upload_time, stored_filename) VALUES (%s, %s, %s, %s, %s, %s, %s)
2025-07-13 22:23:13,228 - sqlalchemy.engine.Engine - INFO - [generated in 0.00135s] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372', 'userid_123', '绘图4.eddx', 53466, 'application/octet-stream', datetime.datetime(2025, 7, 13, 22, 23, 13, 228117), 'userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx')
2025-07-13 22:23:13,235 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-07-13 22:23:13,248 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 22:23:13,248 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.id = %s
2025-07-13 22:23:13,248 - sqlalchemy.engine.Engine - INFO - [generated in 0.00103s] (4,)
2025-07-13 22:23:13,263 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-13 22:28:45,969 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 22:28:45,969 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 22:28:45,975 - sqlalchemy.engine.Engine - INFO - [cached since 332.8s ago] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 22:28:45,988 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-07-13 23:04:42,313 - asyncio - DEBUG - Using proactor: IocpProactor
2025-07-13 23:06:26,442 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-13 23:06:26,474 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-07-13 23:06:26,475 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 23:06:26,481 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-07-13 23:06:26,482 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 23:06:26,486 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-07-13 23:06:26,487 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 23:06:26,493 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 23:06:26,501 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 23:06:26,502 - sqlalchemy.engine.Engine - INFO - [generated in 0.00120s] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 23:06:26,506 - __main__ - DEBUG - Found file metadata for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372
2025-07-13 23:06:26,508 - __main__ - DEBUG - Deleted file userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx from storage.
2025-07-13 23:06:26,512 - __main__ - ERROR - Failed to delete file with file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372: A transaction is already begun on this Session.
2025-07-13 23:06:26,514 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-13 23:17:34,940 - asyncio - DEBUG - Using proactor: IocpProactor
2025-07-13 23:17:45,082 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-13 23:17:45,115 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-07-13 23:17:45,119 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 23:17:45,121 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-07-13 23:17:45,127 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 23:17:45,127 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-07-13 23:17:45,127 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-07-13 23:17:45,127 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 23:17:45,149 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 23:17:45,150 - sqlalchemy.engine.Engine - INFO - [generated in 0.00120s] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 23:17:45,154 - __main__ - DEBUG - Found file metadata for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372
2025-07-13 23:17:45,155 - __main__ - DEBUG - Deleted file userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx from storage.
2025-07-13 23:17:45,155 - __main__ - ERROR - Failed to delete file with file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372: A transaction is already begun on this Session.
2025-07-13 23:17:45,155 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-13 23:18:48,384 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-13 23:18:48,394 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-13 23:18:48,394 - sqlalchemy.engine.Engine - INFO - SELECT file_metadata.id, file_metadata.file_id, file_metadata.user_id, file_metadata.filename, file_metadata.file_size, file_metadata.file_type, file_metadata.upload_time, file_metadata.stored_filename 
FROM file_metadata 
WHERE file_metadata.file_id = %s
2025-07-13 23:18:48,394 - sqlalchemy.engine.Engine - INFO - [cached since 63.25s ago] ('fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372',)
2025-07-13 23:18:48,401 - __main__ - DEBUG - Found file metadata for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372
2025-07-13 23:18:48,401 - __main__ - DEBUG - Deleted file userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx from storage.
2025-07-13 23:18:48,401 - __main__ - ERROR - Failed to delete file with file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372: A transaction is already begun on this Session.
2025-07-13 23:18:48,401 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-14 16:17:47,305 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-07-14 16:17:47,307 - python_multipart.multipart - DEBUG - Calling on_header_field with data[36:55]
2025-07-14 16:17:47,307 - python_multipart.multipart - DEBUG - Calling on_header_value with data[57:104]
2025-07-14 16:17:47,307 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 16:17:47,307 - python_multipart.multipart - DEBUG - Calling on_header_field with data[106:118]
2025-07-14 16:17:47,307 - python_multipart.multipart - DEBUG - Calling on_header_value with data[120:144]
2025-07-14 16:17:47,307 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 16:17:47,309 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-07-14 16:17:47,309 - python_multipart.multipart - DEBUG - Calling on_part_data with data[148:53614]
2025-07-14 16:17:47,309 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-07-14 16:17:47,309 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-07-14 16:17:47,358 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 16:17:47,448 - be.api_services.file_management_service - ERROR - File upload failed for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372: Failed to save file metadata to database: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "D:\VSCode\insight-flow\be\api_services\file_management_service.py", line 129, in upload_file
    await db_mgr.add(metadata)
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\VSCode\insight-flow\be\api_services\file_management_service.py", line 134, in upload_file
    raise DatabaseError(f"Failed to save file metadata to database: {e}") from e
be.common.exceptions.DatabaseError: Failed to save file metadata to database: object NoneType can't be used in 'await' expression
2025-07-14 16:46:43,634 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-07-14 16:46:43,634 - python_multipart.multipart - DEBUG - Calling on_header_field with data[36:55]
2025-07-14 16:46:43,634 - python_multipart.multipart - DEBUG - Calling on_header_value with data[57:104]
2025-07-14 16:46:43,634 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 16:46:43,634 - python_multipart.multipart - DEBUG - Calling on_header_field with data[106:118]
2025-07-14 16:46:43,638 - python_multipart.multipart - DEBUG - Calling on_header_value with data[120:144]
2025-07-14 16:46:43,639 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 16:46:43,639 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-07-14 16:46:43,639 - python_multipart.multipart - DEBUG - Calling on_part_data with data[148:53614]
2025-07-14 16:46:43,639 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-07-14 16:46:43,639 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-07-14 16:46:43,681 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 16:46:43,741 - be.api_services.file_management_service - ERROR - File upload failed for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372: Failed to save file metadata to database: 'AsyncSession' object has no attribute 'save_file_metadata'
Traceback (most recent call last):
  File "D:\VSCode\insight-flow\be\api_services\file_management_service.py", line 120, in upload_file
    await db_mgr.save_file_metadata(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AsyncSession' object has no attribute 'save_file_metadata'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\VSCode\insight-flow\be\api_services\file_management_service.py", line 131, in upload_file
    raise DatabaseError(f"Failed to save file metadata to database: {e}") from e
be.common.exceptions.DatabaseError: Failed to save file metadata to database: 'AsyncSession' object has no attribute 'save_file_metadata'
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_header_field with data[36:55]
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_header_value with data[57:104]
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_header_field with data[106:118]
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_header_value with data[120:144]
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_part_data with data[148:53614]
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-07-14 16:51:06,499 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-07-14 16:51:06,546 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 17:39:13,233 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 17:39:13,258 - be.api_services.file_management_service - DEBUG - Found file metadata for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372
2025-07-14 17:39:13,258 - be.api_services.file_management_service - DEBUG - Deleted file userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx from storage.
2025-07-14 17:39:13,289 - be.api_services.file_management_service - ERROR - Failed to delete file with file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372: Instance '<FileMetadata at 0x2a6aeb0e350>' is not persistent within this Session
2025-07-14 21:59:46,144 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-07-14 21:59:46,145 - python_multipart.multipart - DEBUG - Calling on_header_field with data[36:55]
2025-07-14 21:59:46,146 - python_multipart.multipart - DEBUG - Calling on_header_value with data[57:104]
2025-07-14 21:59:46,146 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 21:59:46,147 - python_multipart.multipart - DEBUG - Calling on_header_field with data[106:118]
2025-07-14 21:59:46,148 - python_multipart.multipart - DEBUG - Calling on_header_value with data[120:144]
2025-07-14 21:59:46,148 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 21:59:46,149 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-07-14 21:59:46,149 - python_multipart.multipart - DEBUG - Calling on_part_data with data[148:53614]
2025-07-14 21:59:46,150 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-07-14 21:59:46,150 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-07-14 21:59:46,201 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 22:00:36,814 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 22:00:36,831 - be.api_services.file_management_service - DEBUG - Found file metadata for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372
2025-07-14 22:00:36,833 - be.api_services.file_management_service - DEBUG - Deleted file userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx from storage.
2025-07-14 22:00:36,857 - be.api_services.file_management_service - ERROR - Failed to delete file with file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372: Instance '<FileMetadata at 0x1ffeaf98e90>' is not persistent within this Session
2025-07-14 22:54:29,226 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-07-14 22:54:29,226 - python_multipart.multipart - DEBUG - Calling on_header_field with data[36:55]
2025-07-14 22:54:29,226 - python_multipart.multipart - DEBUG - Calling on_header_value with data[57:104]
2025-07-14 22:54:29,226 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 22:54:29,229 - python_multipart.multipart - DEBUG - Calling on_header_field with data[106:118]
2025-07-14 22:54:29,229 - python_multipart.multipart - DEBUG - Calling on_header_value with data[120:144]
2025-07-14 22:54:29,229 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 22:54:29,229 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-07-14 22:54:29,229 - python_multipart.multipart - DEBUG - Calling on_part_data with data[148:53614]
2025-07-14 22:54:29,229 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-07-14 22:54:29,229 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-07-14 22:54:29,266 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 22:55:06,141 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 22:55:06,157 - be.api_services.file_management_service - DEBUG - Found file metadata for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372
2025-07-14 22:55:06,161 - be.api_services.file_management_service - DEBUG - Deleted file userid_123_fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372_绘图4.eddx from storage.
2025-07-14 22:55:06,187 - be.api_services.file_management_service - DEBUG - Deleted file metadata for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372.
2025-07-14 22:55:06,190 - be.api_services.file_management_service - INFO - Deleted file status for file_id fa43b6889c67ccb96dfcc6d06ad01602b4631a87521d3fd5fbc0bc4195d84372 from Redis.
2025-07-14 23:07:25,179 - python_multipart.multipart - DEBUG - Calling on_part_begin with no data
2025-07-14 23:07:25,179 - python_multipart.multipart - DEBUG - Calling on_header_field with data[36:55]
2025-07-14 23:07:25,179 - python_multipart.multipart - DEBUG - Calling on_header_value with data[57:104]
2025-07-14 23:07:25,179 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 23:07:25,182 - python_multipart.multipart - DEBUG - Calling on_header_field with data[106:118]
2025-07-14 23:07:25,182 - python_multipart.multipart - DEBUG - Calling on_header_value with data[120:144]
2025-07-14 23:07:25,182 - python_multipart.multipart - DEBUG - Calling on_header_end with no data
2025-07-14 23:07:25,183 - python_multipart.multipart - DEBUG - Calling on_headers_finished with no data
2025-07-14 23:07:25,183 - python_multipart.multipart - DEBUG - Calling on_part_data with data[148:53614]
2025-07-14 23:07:25,183 - python_multipart.multipart - DEBUG - Calling on_part_end with no data
2025-07-14 23:07:25,183 - python_multipart.multipart - DEBUG - Calling on_end with no data
2025-07-14 23:07:25,183 - aioredis - DEBUG - Creating tcp connection to ('192.168.31.233', 6379)
2025-07-14 23:07:25,194 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<RedisConnection._read_data() done, defined at D:\Program Files\Python311\Lib\site-packages\aioredis\connection.py:180> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at D:\Program Files\Python311\Lib\site-packages\aioredis\connection.py:168]>
